[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
life_metric = "4sRLTSXDWEiPGjE85yPyrs5BwJXiFWkooTiXxncGWFQz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/logan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
